name: Deploy to Railway

on:
  push:
    branches:
      - main  # This deploys when there is a push to the main branch
  pull_request:
    branches:
      - main  # This will trigger deployment when there's a PR to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The job will run on an Ubuntu machine

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # This checks out your code from GitHub

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python for the workflow
        with:
          python-version: '3.x'  # Specify the Python version you want (can be 3.10 or 3.13)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your app's dependencies

      - name: Railway CLI login
        uses: railwayapp/railway-action@v1  # Log into Railway using GitHub Actions
        with:
          token: ${{ secrets.RAILWAY_API_TOKEN }}  # This token should be stored in GitHub secrets

      - name: Deploy to Railway
        run: railway up --project ${{ secrets.RAILWAY_PROJECT_ID }}  # Deploy to Railway using the CLI
